
# Example file, change Sample names, fastq_path, number of replicas (comment out the numbers which you don't have),
# adapters (identified with fastqc, shall be cutted by cutadapt)

samples: # change sample name and corresponding SRA number
  Uninjured_input: "SRX1799048"
  Uninjured_chip_rep1: "SRX1799049"
  Uninjured_chip_rep2: "SRX1799050"
  14dpi_input: "SRX1799052"
  14dpi_chip_rep1: "SRX1799053"
  14dpi_chip_rep2: "SRX1799054"
  7dpt_input: "SRX1799055"
  7dpt_chip_rep1: "SRX1799056"
  7dpt_chip_rep2: "SRX1799057"
  
fastq_path: # change to your <Projectdir>/data path
    "/fast/AG_Lab/user/0_Projects/dataset1/data/"
    
reads:
- 1

replicas: #comment out, what you don't have
- 1
- 2
- 3

bigWigs: #change samples names, recommended according to the name used with "samples"
- Uninjured_chip_rep1
- Uninjured_chip_rep2
- 14dpi_chip_rep1
- 14dpi_chip_rep2
- 7dpt_chip_rep1
- 7dpt_chip_rep2

adapters: #add your identified adapter sequences here
- TCGTCGGCAGCGTCAGATGTGTATAAGAGACAG 
- GTCTCGTGGGCTCGGAGATGTGTATAAGAGACAG

